import React, { useState, useEffect } from 'react';

const DeploymentView = ({ API_URL }) => {
  const [deployData, setDeployData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDeploy = async () => {
      try {
        const res = await fetch(`${API_URL}/api/deploy/status`);
        const data = await res.json();
        setDeployData(data);
      } catch (err) {
        console.error("Failed to fetch deploy data:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchDeploy();
  }, [API_URL]);

  return (
    <div style={{ padding: '24px', height: '100%', overflowY: 'auto', backgroundColor: 'var(--app-bg)' }}>
      <h2 style={{ display: 'flex', alignItems: 'center', gap: '10px', color: 'var(--text-primary)', marginTop: 0 }}>
        <span style={{ fontSize: '1.5rem' }}>🚀</span> DevOps & Deployment
      </h2>
      <p style={{ color: 'var(--text-secondary)' }}>
        Infrastructure as Code (IaC) configurations and deployment status generated by the yAI DevOps Expert.
      </p>
      
      {loading ? (
        <div style={{ color: 'var(--text-secondary)', marginTop: '20px' }}>Checking infrastructure status...</div>
      ) : deployData ? (
        <div style={{ marginTop: '30px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div className="dashboard-glass-card" style={{ padding: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h4 style={{ margin: 0, color: 'var(--accent)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span className="status-dot"></span> {deployData.environment}
              </h4>
              <span style={{ fontSize: '0.8rem', color: '#10b981', background: 'rgba(16, 185, 129, 0.1)', padding: '4px 8px', borderRadius: '4px' }}>{deployData.status} ({deployData.uptime})</span>
            </div>
            {deployData.docker_compose && (
              <pre style={{ margin: 0, padding: '12px', background: '#050505', borderRadius: '8px', fontSize: '0.85rem', color: '#a3a3a3', overflowX: 'auto' }}>
                {deployData.docker_compose}
              </pre>
            )}
          </div>
          
          <div className="dashboard-glass-card" style={{ padding: '20px', opacity: 0.7 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h4 style={{ margin: 0, color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#64748b' }}></span> Vercel Production CI/CD
              </h4>
              <span style={{ fontSize: '0.8rem', color: '#94a3b8', background: 'rgba(148, 163, 184, 0.1)', padding: '4px 8px', borderRadius: '4px' }}>
                {deployData.ci_cd_configured ? "Configured" : "Pending Push"}
              </span>
            </div>
          </div>
        </div>
      ) : (
        <div style={{ color: 'var(--text-secondary)' }}>Failed to load deployment data.</div>
      )}
    </div>
  );
};

export default DeploymentView;
