import React from 'react';
import { motion } from 'framer-motion';

export const MarqueeTestimonials = ({
  title = "Loved by thousands of teams"
}) => {
  const testimonials = [
    { text: "This completely changed how we ship products. Incredibly fast.", author: "Sarah Jenkins, CTO" },
    { text: "The UI components are beautiful and saved us months of work.", author: "Mark Davis, Indie Hacker" },
    { text: "Unbelievable quality out of the box. Highly recommended.", author: "Elena Rodriguez, Designer" },
    { text: "We scaled to 1M users seamlessly using this architecture.", author: "David Chen, VP Eng" },
    { text: "The cleanest codebase I have ever seen generated by AI.", author: "Alex Thompson, Founder" }
  ];

  // Duplicate for seamless loop
  const scrollItems = [...testimonials, ...testimonials];

  return (
    <section className="py-24 bg-muted/30 overflow-hidden text-foreground">
      <div className="container mx-auto px-4 text-center mb-12">
        <h2 className="text-3xl font-bold tracking-tight">{title}</h2>
      </div>
      
      <div className="relative w-full flex overflow-x-hidden">
        {/* Left Gradient Fade */}
        <div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-background to-transparent z-10 pointer-events-none" />
        
        <motion.div 
          className="flex whitespace-nowrap gap-6 py-4"
          animate={{ x: ["0%", "-50%"] }}
          transition={{ ease: "linear", duration: 30, repeat: Infinity }}
        >
          {scrollItems.map((item, idx) => (
            <div 
              key={idx} 
              className="w-80 sm:w-96 p-6 rounded-2xl bg-card border border-border shrink-0 flex flex-col justify-between"
            >
              <p className="text-lg italic text-muted-foreground mb-6 whitespace-normal">"{item.text}"</p>
              <p className="font-semibold text-sm">{item.author}</p>
            </div>
          ))}
        </motion.div>
        
        {/* Right Gradient Fade */}
        <div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-background to-transparent z-10 pointer-events-none" />
      </div>
    </section>
  );
};
