import re
import posixpath
from backend.orchestrator.state import AiONState
from backend.utils.logger import get_logger, measure_time

logger = get_logger(__name__)

class ProjectCompletenessAgent:
    """
    Project Completeness Agent (Validator Layer).
    Checks that every expected file was successfully generated by the Coder.
    Also scans for missing React imports that weren't even in the blueprint.
    Routes back to Coder (Recovery Mode) if anything is missing.
    """
    def __init__(self):
        pass

    @measure_time(logger)
    def run(self, state: AiONState, q=None) -> AiONState:
        project_id = state.get("project_id")
        if not q:
            try:
                from backend.api_real import stream_queues
                q = stream_queues.get(project_id)
            except ImportError:
                q = None

        if q:
            q.put({"type": "agent_state", "agent": "reviewer"})
            q.put({"type": "timeline", "title": "Project Completeness", "reason": "Verifying all files and imports exist", "status": "active"})
            q.put({"type": "progress", "message": "🔎 Checking project completeness..."})

        logger.info("[Completeness] Verifying generated files against blueprint...")

        blueprint = state.get("blueprint", {})
        expected_files = set(blueprint.get("file_structure", []))
        
        code_files = state.get("code_files", {})
        generated_files = set(code_files.keys())

        missing_files = expected_files - generated_files

        # Scan for missing internal imports in React/JS files
        import_regex = re.compile(r'import\s+(?:.*?\s+from\s+)?[\'"]([./].*?)[\'"]')
        
        basename_to_paths = {}
        for fp in generated_files:
            basename = posixpath.basename(fp).split('.')[0]
            if basename not in basename_to_paths:
                basename_to_paths[basename] = []
            basename_to_paths[basename].append(fp)

        for file_path, content in code_files.items():
            if not file_path.endswith(('.js', '.jsx', '.ts', '.tsx')):
                continue
                
            dir_path = posixpath.dirname(file_path)
            matches = import_regex.findall(content)
            
            for match in matches:
                # Resolve relative path
                resolved_path = posixpath.normpath(posixpath.join(dir_path, match))
                
                possible_paths = [
                    resolved_path,
                    f"{resolved_path}.jsx",
                    f"{resolved_path}.js",
                    f"{resolved_path}.tsx",
                    f"{resolved_path}.ts",
                    f"{resolved_path}.css",
                    f"{resolved_path}/index.jsx",
                    f"{resolved_path}/index.js"
                ]
                
                if not any(p in code_files for p in possible_paths):
                    # Check if it exists elsewhere in the project
                    target_basename = posixpath.basename(match).split('.')[0]
                    if target_basename not in basename_to_paths:
                        target_missing = f"{resolved_path}.jsx" if not '.' in match.split('/')[-1] else resolved_path
                        missing_files.add(target_missing)
                        logger.warning(f"   -> [Missing Import] '{file_path}' requires '{target_missing}'")

        state["missing_dependencies"] = list(missing_files)

        if missing_files:
            logger.warning(f"[Completeness] ⚠️ Missing {len(missing_files)} files: {list(missing_files)[:5]}")
            if q:
                q.put({"type": "progress", "message": f"⚠️ Missing {len(missing_files)} files. Spawning Recovery Agent..."})
        else:
            logger.info("[Completeness] ✅ Project is fully complete.")
            if q:
                q.put({"type": "progress", "message": "✅ Project completeness verified."})

        return state
